---

build: off

cache:
- C:\ProgramData\chocolatey\lib -> appveyor.yml

before_test:
- choco install ghc
- choco install cabal
- choco install 7zip

test_script:
- refreshenv
- cabal update
- cabal new-build all
- ps: $directory = Get-ChildItem . -name -recurse atspkg.exe
- ps: Copy-Item $directory atspkg-x86_64-pc-windows.exe
- ps: Push-AppveyorArtifact atspkg-x86_64-pc-windows.exe

deploy:
  artifacts: atspkg-x86_64-pc-windows.exe
  provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: cNzi4ZEE4PIrKxBJXEDPHkqrHI4fdSJtIQZ8n7qbYJwBtsx8TkBxduK8eIr6fzdY

branches:
  only:
  - master
  - /\d+\.\d+\.\d+\.\d+.*$/
